# =====================================================================================
# Generated by EyesofBucket Configs
# DO NOT EDIT MANUALLY
# Update script:
# bash -c "$(curl -fsSL https://raw.github.com/eyesofBucket/configs/main/update.sh)" ""
# =====================================================================================

alias watch='watch '
alias sudo='sudo '
alias please='sudo '
alias svim='sudoedit'

alias colormap='for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+"\n"}; done'

alias pubip='curl ifconfig.io'

# Debian
if which apt >/dev/null 2>&1
then
    alias update='sudo apt update && sudo apt upgrade -y'

# Fedora
elif which yum >/dev/null 2>&1
then
    alias update='sudo yum update -y'

# Arch
elif which pacman >/dev/null 2>&1
then
    alias update='sudo pacman -Syu'
fi

# podman
if which podman >/dev/null 2>&1
then
    alias pm='podman'
    alias pml='podman logs'
    alias pmp='podman pod'
    
    alias pmi='podman image'
    alias pmip='podman image prune'

    alias pps='podman ps --format '\''table {{.Names}}\t{{.Status}}\t{{.Ports}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'
    alias ppq='podman ps --format '\''table {{.Names}}\t{{.Status}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'
    alias ppa='podman ps --format '\''table {{.Names}}\t{{.Status}}\t{{.Networks}}\t{{.Ports}}\t{{.Image}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'

    alias pin='podman inspect'
    alias pmstart='podman start'
    alias pmstop='podman stop'
    alias pmr='podman restart'

    alias pn='podman network'
    alias pni='podman network inspect'
    alias pnl='podman network ls'
    alias pnc='podman network connect'
    alias pnd='podman network disconnect'

    # sudo podman
    alias spm='sudo podman'
    alias spml='sudo podman logs'
    alias spmp='sudo podman pod'

    alias spmi='sudo podman image'
    alias spmip='sudo podman image prune'

    alias spps='sudo podman ps --format '\''table {{.Names}}\t{{.Status}}\t{{.Ports}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'
    alias sppq='sudo podman ps --format '\''table {{.Names}}\t{{.Status}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'
    alias sppa='sudo podman ps --format '\''table {{.Names}}\t{{.Status}}\t{{.Networks}}\t{{.Ports}}\t{{.Image}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'

    alias spin='sudo podman inspect'
    alias spmstart='sudo podman start'
    alias spmstop='sudo podman stop'
    alias spmr='sudo podman restart'

    alias spn='sudo podman network'
    alias spni='sudo podman network inspect'
    alias spnl='sudo podman network ls'
    alias spnc='sudo podman network connect'
    alias spnd='sudo podman network disconnect'
fi

# podman-compose
if which podman-compose >/dev/null 2>&1
then
    alias pc='podman-compose'
    alias pcu='podman-compose pull && podman-compose up -d'
    alias pcr='podman-compose down && podman-compose up -d'
    alias pcd='podman-compose down'

    # sudo podman-compose
    alias spc='sudo /usr/local/bin/podman-compose'
    alias spcu='sudo /usr/local/bin/podman-compose pull && sudo /usr/local/bin/podman-compose up -d'
    alias spcr='sudo /usr/local/bin/podman-compose down && sudo /usr/local/bin/podman-compose up -d'
    alias spcd='sudo /usr/local/bin/podman-compose down'
fi

# docker
if which docker >/dev/null 2>&1
then
    alias dk='docker'
    alias dl='docker logs'

    alias di='docker image'
    alias dip='docker image prune'

    alias dps='docker ps --format '\''table {{.Names}}\t{{.Status}}\t{{.Ports}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'
    alias dpq='docker ps --format '\''table {{.Names}}\t{{.Status}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'
    alias dpa='docker ps --format '\''table {{.Names}}\t{{.Status}}\t{{.Networks}}\t{{.Ports}}\t{{.Image}}'\'' -a | (read -r; printf "%s\n" "$REPLY"; sort)'

    alias din='docker inspect'
    alias dstart='docker start'
    alias dstop='docker stop'
    alias dr='docker restart'

    alias dn='docker network'
    alias dni='docker network inspect'
    alias dnl='docker network ls'
    alias dnc='docker network connect'
    alias dnd='docker network disconnect'

    # For the compose plugin.  Gets overwritten if docker-compose still exists
    alias dc='docker compose'
    alias dcu='docker compose pull && docker compose up -d'
    alias dcr='docker compose down && docker compose up -d'
    alias dcd='docker compose down'
fi

# docker-compose
if which docker-compose >/dev/null 2>&1
then
    alias dc='docker-compose'
    alias dcu='docker-compose pull && docker-compose up -d'
    alias dcr='docker-compose down && docker-compose up -d'
    alias dcd='docker-compose down'
fi

# firewall-cmd
if which firewall-cmd >/dev/null 2>&1
then
    alias fw='sudo firewall-cmd'
    alias fws='sudo firewall-cmd --state'
    alias fwl='sudo firewall-cmd --list-all'

    alias fwr='sudo firewall-cmd --reload'
    alias fwcr='sudo firewall-cmd --complete-reload'

    alias fwap='sudo firewall-cmd --add-port'
    alias fwapp='sudo firewall-cmd --permanent --add-port'
    alias fwrp='sudo firewall-cmd --remove-port'
    alias fwrpp='sudo firewall-cmd --permanent --remove-port'

    alias fwas='sudo firewall-cmd --add-service'
    alias fwasp='sudo firewall-cmd --permanent --add-service'
    alias fwrs='sudo firewall-cmd --remove-service'
    alias fwrsp='sudo firewall-cmd --permanent --remove-service'
fi