#!/usr/bin/env bash

[[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    options=$(grep -i '^host.*' "${HOME}/.ssh/config" | grep -iv '# *hidden' | awk '{print $2}')
    selected=$(echo "$options" | fzf --print-query | tail -1)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected" "ssh $selected"
fi

tmux "$change" -t "$selected_name"
