#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    options=$(find ~/projects -mindepth 1 -maxdepth 1 -type d | tr -s '\n' ';')
    options="$options;$HOME/bvkt"
    selected=$(echo $options | tr -s ';' '\n' | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    tmux new-window -t ${selected_name}: nvim .
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi

