#!/usr/bin/env bash

[[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    options="$(find $(echo $BVKT_PROJECT_DIRS | tr -s ';' ' ') -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' | tr -s '\n' ';');$BVKT_PROJECTS"
    selected=$(echo $options | tr -s ';' '\n' | fzf --preview "eza --icons --git --git-repos -gTl --color=always {}")
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
    tmux new-window -t "${selected_name}:" -c "$selected" -n 'neovim' 'nvim .; zsh'
fi

tmux "$change" -t "$selected_name"
