#!/usr/bin/env bash

[[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"

session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --print-query | tail -1)

if [[ -z "$session" ]]; then exit; fi

if ! tmux has-session -t="$session" 2> /dev/null; then
    tmux new-session -d -s "$session"
fi

tmux "$change" -t "$session"
